- id: '1737981880348'
  alias: Heizung - Fenster - Wohnzimmer
  description: ''
  use_blueprint:
    path: panhans/advanced_heating_control.yaml
    input:
      input_trvs:
      - climate.wohnzimmer
      input_temperature_sensor: sensor.wohnzimmer_temperatur
      input_windows:
      - binary_sensor.hue_secure_contact_sensor_1_offnung
      - binary_sensor.hue_secure_contact_sensor_2_offnung
      input_windows_reaction_time_open:
        hours: 0
        minutes: 0
        seconds: 10
      input_windows_reaction_time_close:
        hours: 0
        minutes: 0
        seconds: 10
      input_window_legacy_restore: false
      input_mode_winter: input_boolean.heizsaison
- id: '1737982506936'
  alias: Heizung - Fenster - Kinderzimmer
  description: ''
  use_blueprint:
    path: panhans/advanced_heating_control.yaml
    input:
      input_trvs:
      - climate.kinderzimmer
      input_temperature_sensor: sensor.multisensor_kinderzimmer_temperatur
      input_windows:
      - binary_sensor.fenster_kinderzimmer_offnung
      input_windows_reaction_time_open:
        hours: 0
        minutes: 0
        seconds: 10
      input_windows_reaction_time_close:
        hours: 0
        minutes: 0
        seconds: 10
      input_window_legacy_restore: false
      input_mode_winter: input_boolean.heizsaison
- id: '1738068160611'
  alias: Update Benachrichtigung
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      mobile_app_device: cf5ce63e7db97fd06d15fc47cd80d9bc
      update_entities:
      - update.home_assistant_core_update
      - update.home_assistant_operating_system_update
      - update.home_assistant_supervisor_update
      - update.hacs_update
      run_config_check: true
      only_after: '13:00:00'
      only_before: '22:00:00'
      send_to_ha: true
      mobile_app_device_2: cf5ce63e7db97fd06d15fc47cd80d9bc
- id: '1738149564542'
  alias: Batterie-Warnung mit Ausschlüssen
  description: Prüft täglich alle Batterie-Sensoren außer bestimmte ausgeschlossene
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - variables:
      excluded_entities:
      - sensor.alissa_iphone_battery_level
      - sensor.rita_iphone_battery_level
      - sensor.rita_iphone_watch_battery_level
      - sensor.wowa_iphone_battery_level
      - sensor.wowa_iphone_watch_battery
      - binary_sensor.va1406739968_batterie
      - binary_sensor.va2883396096_batterie
      - sensor.battery_min
      - sensor.devices_with_low_battery
      threshold: 15
      low_batteries: "{% set low = namespace(devices=[]) %} {% for entity in states.sensor
        %}\n  {% if 'battery' in entity.entity_id and entity.entity_id not in excluded_entities
        %}\n    {% if entity.state not in ['unknown', 'unavailable'] %}\n      {%
        if entity.state | int(default=100) < threshold %}\n        {% set name = entity.name
        %}\n        {% set level = entity.state %}\n        {% set dev = name ~ \"
        (\" ~ level ~ \"%)\" %}\n        {% set low.devices = low.devices + [dev]
        %}\n      {% endif %}\n    {% endif %}\n  {% endif %}\n{% endfor %} {{ low.devices
        }}"
  - choose:
    - conditions: '{{ low_batteries | length > 0 }}'
      sequence:
      - service: notify.mobile_app_wowa_iphone
        data:
          title: Batterie-Warnung
          message: 'Folgende Geräte haben einen niedrigen Batteriestand: {{ low_batteries
            | join(", ") }}'
  mode: single
- id: '1777541886385'
  alias: Weihnachtenzeit Aktivierung
  description: ''
  triggers:
  - trigger: state
    entity_id: binary_sensor.christmas_time
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.christmas_time
        state: 'on'
      sequence:
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.christmas_automation
      - action: automation.turn_on
        target:
          entity_id: automation.weihnachtsbeleuchtung
    - conditions:
      - condition: state
        entity_id: binary_sensor.christmas_time
        state: 'off'
      sequence:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.christmas_automation
      - action: automation.turn_off
        target:
          entity_id: automation.weihnachtsbeleuchtung
  mode: single
- id: '1777541933138'
  alias: Weihnachtsbeleuchtung Steuerung (AN & AUS & Sofort AUS)
  description: Kombinierte Automation für Weihnachtsbeleuchtung
  triggers:
  - trigger: time
    at: 06:30:00
    id: on_time_morning
  - trigger: time
    at: 08:00:00
    id: off_time_morning
  - trigger: time
    at: '16:30:00'
    id: on_time_afternoon
  - trigger: time
    at: '23:00:00'
    id: off_time_afternoon
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id: on_time_morning
      - condition: state
        entity_id: input_boolean.christmas_automation
        state: 'on'
      sequence:
      - action: light.turn_on
        target:
          entity_id: light.little_xmas_tree
    - conditions:
      - condition: trigger
        id: off_time_morning
      - condition: state
        entity_id: input_boolean.christmas_automation
        state: 'on'
      sequence:
      - action: light.turn_off
        target:
          entity_id: light.little_xmas_tree
    - conditions:
      - condition: trigger
        id: on_time_afternoon
      - condition: state
        entity_id: input_boolean.christmas_automation
        state: 'on'
      sequence:
      - action: light.turn_on
        target:
          entity_id: light.little_xmas_tree
    - conditions:
      - condition: trigger
        id: off_time_afternoon
      - condition: state
        entity_id: input_boolean.christmas_automation
        state: 'on'
      sequence:
      - action: light.turn_off
        target:
          entity_id: light.little_xmas_tree
  mode: single
- id: '1778409652157'
  alias: Alarm - Auslöser - Armed Away
  description: Auslösen, wenn Bewegung erkannt wird und keiner zu Hause ist.
  triggers:
  - trigger: state
    entity_id: binary_sensor.eingangstur_offnung
    to: 'on'
  - trigger: state
    entity_id: binary_sensor.hue_bewegungssensor_flur_bewegung
    to: 'on'
  conditions:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  actions:
  - delay: 00:00:05
  - action: notify.mobile_app_wowa_iphone
    data:
      message: ALARM - Bewegung zu Hause registriert!
  mode: single
- id: '1778409705716'
  alias: Alarm - Auslöser - Armed Home
  description: Auslösen, wenn Bewegung erkannt wird.
  triggers:
  - trigger: state
    entity_id: binary_sensor.eingangstur_offnung
    to: 'on'
  - trigger: state
    entity_id: binary_sensor.bewegungsmelder_treppenhaus_belegung
    to: 'on'
  conditions:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_home
  actions:
  - delay: 00:00:05
  - action: notify.mobile_app_wowa_iphone
    data:
      message: ALARM! Bewegung im Treppenhaus registriert!
  - action: tts.google_translate_say
    data:
      entity_id: media_player.wohnzimmer
      message: ALARM! Bewegung im Treppenhaus registriert!
      language: de
      cache: true
    enabled: true
  mode: single
- id: '1778409786662'
  alias: AWIDO Termine sync – 100 Tage, ohne Duplikate, ganztägig
  description: Kopiert AWIDO-Termine von awido_online nach awido, ohne Duplikate
  triggers:
  - trigger: time
    at: 01:00:00
  conditions: []
  actions:
  - action: calendar.get_events
    target:
      entity_id: calendar.awido_online
    data:
      duration:
        days: 100
    response_variable: quelle
  - action: calendar.get_events
    target:
      entity_id: calendar.awido
    data:
      duration:
        days: 100
    response_variable: ziel
  - variables:
      source_events: '{{ quelle[''calendar.awido_online''][''events''] }}'
      target_events: '{{ ziel[''calendar.awido''][''events''] }}'
  - repeat:
      for_each: '{{ source_events }}'
      sequence:
      - variables:
          exists: "{% set src_date = as_datetime(repeat.item.start).date() %} {% set
            src_summary = repeat.item.summary %} {% set ns = namespace(found=false)
            %} {% for ev in target_events %}\n  {% set tgt_date = as_datetime(ev.start).date()
            %}\n  {% if ev.summary == src_summary and tgt_date == src_date %}\n    {%
            set ns.found = true %}\n  {% endif %}\n{% endfor %} {{ ns.found }}\n"
      - if:
        - condition: template
          value_template: '{{ not exists }}'
        then:
        - action: calendar.create_event
          target:
            entity_id: calendar.awido
          data:
            summary: '{{ repeat.item.summary }}'
            description: '{{ repeat.item.description | default('''', true) }}'
            location: '{{ repeat.item.location | default('''', true) }}'
            start_date: '{{ as_datetime(repeat.item.start).date() }}'
            end_date: '{{ (as_datetime(repeat.item.start) + timedelta(days=1)).date()
              }}'
  mode: single
- id: '1778409834261'
  alias: Abfall Benachrichtigung
  description: ''
  triggers:
  - trigger: time
    at: '20:00:00'
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: sensor.waste_collection_notify
      state: '1'
    - condition: state
      entity_id: input_boolean.toggle_button_notify_garbage
      state: 'on'
  actions:
  - action: notify.mobile_app_wowa_iphone
    data:
      title: Abfall Benachrichtigung
      message: '{{ states(''sensor.waste_collection_notify_type'') | replace(''['',
        '''')| replace('']'', '''') | replace(''\'''', '''') }} rausstellen'
  mode: single
- id: '1778410109475'
  alias: Licht Abstellkammer
  description: Licht Abstellkammer an wenn die Türen geöffnet sind und aus wenn die
    Türen geschlossen sind.
  triggers:
  - trigger: state
    entity_id: group.kitchen_doors
  conditions:
  - condition: or
    conditions:
    - before: sunrise
      condition: sun
    - after: sunset
      condition: sun
  actions:
  - action: switch.turn_{{'on' if trigger.to_state.state == 'on' else 'off'}}
    entity_id: switch.light_storeroom_kitchen
  mode: single
- id: '1778410120744'
  alias: Licht Abstellkammer ausschalten
  description: Licht Abstellkammer nach 30 Min. ausschalten
  triggers:
  - trigger: state
    entity_id: switch.light_storeroom_kitchen
    from: 'off'
    to: 'on'
    for: 00:30:00
  conditions: []
  actions:
  - action: switch.turn_off
    entity_id: switch.light_storeroom_kitchen
  mode: single
- id: '1778410164438'
  alias: Dunstabzugshaube
  description: Dunstabzugshaube an wenn das Fenster geöffnet ist und aus, wenn das
    Fenster zu ist.
  triggers:
  - trigger: state
    entity_id: binary_sensor.fenster_kuche
    for: 00:00:05
  conditions: []
  actions:
  - action: switch.turn_{{'on' if trigger.to_state.state == 'on' else 'off'}}
    entity_id: switch.extractor_hood_kitchen
  mode: single
- id: '1778410182579'
  alias: Wasser Leckage Spülmashine
  description: Benachrichtigung bei Wasserleckage unter der Spülmashine
  triggers:
  - trigger: state
    entity_id: binary_sensor.wasserleckage_sensor_kuche_feuchtigkeit
    from: 'off'
    to: 'on'
    for: 00:00:05
  conditions: []
  actions:
  - action: light.turn_on
    target:
      entity_id: light.deckenlicht_kuche
    data:
      flash: short
      brightness_pct: 100
  - action: tts.google_translate_say
    data:
      entity_id: media_player.wohnzimmer
      message: ALARM! Wasserleck in der Küche registriert!
      language: de
      cache: true
    enabled: true
  - action: notify.mobile_app_wowa_iphone
    data:
      message: ALARM! Wasserleck in der Küche registriert!
  mode: single
- id: '1778410220926'
  alias: Nachtlicht Kinderzimmer an
  description: Ambiente um 22:00 Uhr als Nachtlicht einschalten.
  triggers:
  - trigger: time
    at: '21:50:00'
  conditions:
  - condition: state
    entity_id: input_boolean.night_light_nursery
    state: 'on'
  actions:
  - action: light.turn_on
    data:
      entity_id: light.ambiente_rgb
      brightness_pct: 8
  mode: single
- id: '1778410335832'
  alias: Nachtlicht ab 22:00 auf 5% dimmen
  description: Ambiente auf 5% dimmen
  triggers:
  - trigger: time
    at: '22:00:00'
  conditions:
  - condition: state
    entity_id: light.ambiente_rgb
    state: 'on'
  - condition: state
    entity_id: input_boolean.night_light_nursery
    state: 'on'
  actions:
  - action: light.turn_on
    target:
      entity_id: light.ambiente_rgb
    data:
      brightness_pct: 5
  mode: single
- id: '1778410349946'
  alias: Nachtlicht Kinderzimmer aus
  description: Ambiente um 07:10 Uhr ausschalten.
  triggers:
  - trigger: time
    at: 07:10:00
  conditions: []
  actions:
  - action: light.turn_off
    entity_id:
    - light.ambiente_rgb
    - light.ambiente_rgb_2
  mode: single
- id: '1778410404595'
  alias: Philips Hue Flur Motion Manual OFF
  description: ''
  triggers:
  - trigger: state
    entity_id: event.lichtschalter_flur_hinten_schaltflache_3
  - trigger: state
    entity_id: event.lichtschalter_flur_vorne_schaltflache_1
  conditions: []
  actions:
  - action: input_boolean.turn_off
    data:
      entity_id: input_boolean.flurlicht_manual_helper
  mode: single
- id: '1778410413450'
  alias: Philips Hue Flur Motion Manual ON
  description: ''
  triggers:
  - trigger: state
    entity_id: event.lichtschalter_flur_hinten_schaltflache_4
  - trigger: state
    entity_id: event.lichtschalter_flur_vorne_schaltflache_2
  conditions: []
  actions:
  - action: input_boolean.turn_on
    data:
      entity_id: input_boolean.flurlicht_manual_helper
  mode: single
- id: '1778410442888'
  alias: Philips Hue Flur Motion
  description: ''
  triggers:
  - trigger: state
    entity_id: binary_sensor.hue_bewegungssensor_flur_bewegung
    from: 'off'
    to: 'on'
  - trigger: state
    entity_id: binary_sensor.hue_bewegungssensor_flur_bewegung
    from: 'on'
    to: 'off'
    for: 20
  - trigger: state
    entity_id: binary_sensor.hue_bewegungssensor_flur_bewegung
    from: 'on'
    to: 'off'
    for: 40
  conditions:
  - condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: +00:10:00
    - condition: sun
      before: sunrise
      before_offset: -00:10:00
  - condition: state
    entity_id: input_boolean.flurlicht_manual_helper
    state: 'off'
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.to_state.state == ''on'' }}'
      - condition: template
        value_template: '{{ is_state(''light.deckenlicht_flur'', ''off'') }}'
      sequence:
      - action: light.turn_on
        target:
          entity_id: light.deckenlicht_flur
        data:
          brightness_pct: 15
    - conditions:
      - condition: template
        value_template: '{{ trigger.to_state.state == ''off'' }}'
      - condition: template
        value_template: '{{ trigger.for.seconds == 20 }}'
      - condition: template
        value_template: '{{ is_state(''light.deckenlicht_flur'', ''on'') }}'
      sequence:
      - action: light.turn_on
        target:
          entity_id: light.deckenlicht_flur
        data:
          brightness_pct: 5
    - conditions:
      - condition: template
        value_template: '{{ trigger.to_state.state == ''off'' }}'
      - condition: template
        value_template: '{{ trigger.for.seconds == 40 }}'
      - condition: template
        value_template: '{{ is_state(''light.deckenlicht_flur'', ''on'') }}'
      sequence:
      - action: light.turn_off
        target:
          entity_id: light.deckenlicht_flur
  mode: restart
- id: '1778410479673'
  alias: Licht Dachboden ausschalten
  description: Licht Dachboden nach 30 Minuten ausschalten
  triggers:
  - trigger: state
    entity_id: switch.light_attic
    from: 'off'
    to: 'on'
    for: 00:30:00
  conditions: []
  actions:
  - action: switch.turn_off
    entity_id: switch.light_attic
  mode: single
