homeassistant:
  customize:
    #########################################################################
    ## PERSONS
    device_tracker.wowa_iphone:
      entity_picture: /local/device_tracker.svg

    #########################################################################
    ## WOHNZIMMER
    binary_sensor.fenster_wohnzimmer_links_contact:
      friendly_name: Fenster Wohnzimmer links
    binary_sensor.fenster_wohnzimmer_rechts_contact:
      friendly_name: Fenster Wohnzimmer rechts
    switch.gosund_sp111_steckdose_couch:
      friendly_name: Wohnzimmer Steckdose Couch
    switch.gosund_sp111_steckdose_verteiler:
      friendly_name: Wohnzimmer Steckdose Verteiler
    sensor.fenster_wohnzimmer_links_battery:
      friendly_name: Fenster Wohnzimmer links Batterie
    sensor.fenster_wohnzimmer_rechts_battery:
      friendly_name: Fenster Wohnzimmer rechts Batterie
    sensor.multisensor_wohnzimmer_battery:
      friendly_name: Multisensor Wohnzimmer Batterie

    #########################################################################
    ## SCHLAFZIMMER
    binary_sensor.fenster_schlafzimmer_contact:
      friendly_name: Fenster Schlafzimmer
    switch.gosund_sp112_bedroom:
      friendly_name: Schlafzimmer Steckdose Bett
    switch.gosund_sp112_bedroom_usb:
      friendly_name: Schlafzimmer Steckdose USB Bett

    #########################################################################
    ## KINDERZIMMER
    binary_sensor.fenster_kinderzimmer_contact:
      friendly_name: Fenster Kinderzimmer
    switch.gosund_sp112_nursery:
      friendly_name: Kinderzimmer Steckdose Tisch
    switch.gosund_sp112_nursery_usb:
      friendly_name: Kinderzimmer Steckdose USB Tisch
    switch.multimedia_kinderzimmer:
      friendly_name: Kinderzimmer Steckdose Multimedia
    sensor.fenster_kinderzimmer_battery:
      friendly_name: Fenster Kinderzimmer Batterie
    sensor.multisensor_kinderzimmer_battery:
      friendly_name: Multisensor Kinderzimmer Batterie

    #########################################################################
    ## KÜCHE
    binary_sensor.fenster_kuche_contact:
      friendly_name: Fenster Küche
    sensor.multisensor_kuche_battery:
      friendly_name: Multisensor Küche Batterie
    sensor.fenster_kuche_battery:
      friendly_name: Fenster Küche Batterie
    sensor.abstellkammer_tur_rechts_battery:
      friendly_name: Abstellkammer Küche rechts Batterie
    sensor.abstellkammer_tur_links_battery:
      friendly_name: Abstellkammer Küche links Batterie

    #########################################################################
    ## BADEZIMMER
    switch.gosund_sp112_bath:
      friendly_name: Bad Steckdose
    switch.gosund_sp112_bath_usb:
      friendly_name: Bad Steckdose USB
    sensor.multisensor_badezimmer_battery:
      friendly_name: Multisensor Bad Batterie

    #########################################################################
    ## ABSTELLKAMMER
    binary_sensor.fenster_abstellkammer_contact:
      friendly_name: Fenster Abstellkammer Küche

    #########################################################################
    ## NEBENRAUM
    switch.light_storageroom:
      friendly_name: Licht Nebenraum
    switch.light_attic:
      friendly_name: Licht Dachboden

    #########################################################################
    ## KELLER
    switch.light_cellar:
      friendly_name: Licht Keller
