# ----------------------------------------------------------------------------------------------------------------------
# WASTE COLLECTION SHEDULE
waste_collection_schedule:
  sources:
    - name: awido_de
      args:
        customer: !secret waste_customer_value
        city: !secret waste_city_value
        street: !secret waste_street_value
        housenumber: !secret waste_housenumber_value
      customize:
        - type: Restmüll grün 4-wöchentlich
          alias: Restmüll
        - type: Restmüll 14-täglich
          show: False
        - type: Restmüll rot 4-wöchentlich
          show: False
sensor:
  # ------- Garbage Collection -------
  # next collection
  - platform: waste_collection_schedule
    name: "waste_collection_next_collection"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
  # next collection simple
  - platform: waste_collection_schedule
    name: waste_collection_next_type
    value_template: "{{ value.types[0] }}"
  # abfall_heute_aktiv
  - platform: waste_collection_schedule
    name: "abfall_heute_aktiv"
    value_template: "{% if value.daysTo == 0 %} on {% else %} off {% endif %}"
  # abfall_morgen_aktiv
  - platform: waste_collection_schedule
    name: "abfall_morgen_aktiv"
    value_template: "{% if value.daysTo == 1 %} on {% else %} off {% endif %}"

  - platform: waste_collection_schedule
    name: waste_collection_notify
    details_format: "upcoming"
    value_template: "{{value.daysTo}}"

  - platform: waste_collection_schedule
    name: waste_collection_notify_type
    details_format: "upcoming"
    value_template: "{{value.types}}"

  - platform: waste_collection_schedule
    name: waste_collection_waste
    details_format: upcoming
    value_template: "{{value.daysTo}}"
    types:
      - Restmüll

  - platform: waste_collection_schedule
    name: waste_collection_paper
    details_format: upcoming
    value_template: "{{value.daysTo}}"
    types:
      - Papier-Tonne

  - platform: waste_collection_schedule
    name: waste_collection_bio
    details_format: upcoming
    value_template: "{{value.daysTo}}"
    types:
      - Bio-Tonne

  - platform: waste_collection_schedule
    name: waste_collection_plastic
    details_format: upcoming
    value_template: "{{value.daysTo}}"
    types:
      - Gelbe Tonne

  - platform: waste_collection_schedule
    name: waste_collection_bulky_waste
    details_format: upcoming
    value_template: "{{value.daysTo}}"
    types:
      - Sperrmüll

template:
  - sensor:
      - default_entity_id: sensor.waste_collection_type
        state:
          '{{ states(''sensor.waste_collection_notify_type'') | replace("[", "",1)
          | replace("]", "") | replace("''", "") }}'
        name: waste_collection_type

  - sensor:
      - name: "Waste Collection Condition"
        state: >
          {% set state = states('sensor.waste_collection_notify')|float(0) %}{% if state <= 1 %}on{% else %}off{% endif %}